services:
  kafka:
    image: apache/kafka:4.1.1
    container_name: orvd_system-kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft mode
      KAFKA_KRAFT_MODE: "true"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "opbd-cluster-1"
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    networks:
      - drones_net
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: orvd_system-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - C:/msys64/home/niyaz/projects/semester6/cybersecurity/OpBD/systems/orvd_system/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - drones_net
    restart: unless-stopped

networks:
  drones_net:
    external: true